### ISSUE TITLE
Docker issue?

### ISSUE THREAD

**Issue by Deathnetworks** [AeonLucid/FlareSolverr#5]
I'm getting spammed with this via docker, tried running it locally from source and it's running fine... If chrome didn't pop up visibly it'd be workable too. Tried both 3.0.0 and v3beta, original flaresolverr seems to have issues too. My guess is it's a docker only issue, I just copy pasta docker containers so hell if I know, tried running a pip update on the packages, but the thing restarts before the command gets executed

```
2022-12-16 20:58:22 2022-12-16 20:58:22 INFO     FlareSolverr 3.0.0
2022-12-16 20:58:22 2022-12-16 20:58:22 INFO     Testing web browser installation...
2022-12-16 20:58:22 2022-12-16 20:58:22 INFO     Chrome major version: 108
2022-12-16 20:58:29 Traceback (most recent call last):
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
2022-12-16 20:58:29     h.request(req.get_method(), req.selector, req.data, headers,
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2022-12-16 20:58:29     self._send_request(method, url, body, headers, encode_chunked)
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2022-12-16 20:58:29     self.endheaders(body, encode_chunked=encode_chunked)
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2022-12-16 20:58:29     self._send_output(message_body, encode_chunked=encode_chunked)
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2022-12-16 20:58:29     self.send(msg)
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 975, in send
2022-12-16 20:58:29     self.connect()
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 1447, in connect
2022-12-16 20:58:29     super().connect()
2022-12-16 20:58:29   File "/usr/lib/python3.10/http/client.py", line 941, in connect
2022-12-16 20:58:29     self.sock = self._create_connection(
2022-12-16 20:58:29   File "/usr/lib/python3.10/socket.py", line 845, in create_connection
2022-12-16 20:58:29     raise err
2022-12-16 20:58:29   File "/usr/lib/python3.10/socket.py", line 833, in create_connection
2022-12-16 20:58:29     sock.connect(sa)
2022-12-16 20:58:29 OSError: [Errno 113] No route to host
2022-12-16 20:58:29 
2022-12-16 20:58:29 During handling of the above exception, another exception occurred:
2022-12-16 20:58:29 
2022-12-16 20:58:29 Traceback (most recent call last):
2022-12-16 20:58:29   File "/app/utils.py", line 153, in get_user_agent
2022-12-16 20:58:29     driver = get_webdriver()
2022-12-16 20:58:29   File "/app/utils.py", line 70, in get_webdriver
2022-12-16 20:58:29     driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
2022-12-16 20:58:29   File "/app/undetected_chromedriver/__init__.py", line 242, in __init__
2022-12-16 20:58:29     patcher.auto()
2022-12-16 20:58:29   File "/app/undetected_chromedriver/patcher.py", line 127, in auto
2022-12-16 20:58:29     release = self.fetch_release_number()
2022-12-16 20:58:29   File "/app/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
2022-12-16 20:58:29     return LooseVersion(urlopen(self.url_repo + path).read().decode())
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
2022-12-16 20:58:29     return opener.open(url, data, timeout)
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
2022-12-16 20:58:29     response = self._open(req, data)
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
2022-12-16 20:58:29     result = self._call_chain(self.handle_open, protocol, protocol +
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
2022-12-16 20:58:29     result = func(*args)
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
2022-12-16 20:58:29     return self.do_open(http.client.HTTPSConnection, req,
2022-12-16 20:58:29   File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
2022-12-16 20:58:29     raise URLError(err)
2022-12-16 20:58:29 urllib.error.URLError: <urlopen error [Errno 113] No route to host>
2022-12-16 20:58:29 
2022-12-16 20:58:29 During handling of the above exception, another exception occurred:
2022-12-16 20:58:29 
2022-12-16 20:58:29 Traceback (most recent call last):
2022-12-16 20:58:29   File "/app/flaresolverr.py", line 91, in <module>
2022-12-16 20:58:29     flaresolverr_service.test_browser_installation()
2022-12-16 20:58:29   File "/app/flaresolverr_service.py", line 47, in test_browser_installation
2022-12-16 20:58:29     user_agent = utils.get_user_agent()
2022-12-16 20:58:29   File "/app/utils.py", line 157, in get_user_agent
2022-12-16 20:58:29     raise Exception("Error getting browser User-Agent. " + str(e))
2022-12-16 20:58:29 Exception: Error getting browser User-Agent. <urlopen error [Errno 113] No route to host>
2022-12-16 20:58:39 Traceback (most recent call last):
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
2022-12-16 20:58:39     h.request(req.get_method(), req.selector, req.data, headers,
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2022-12-16 20:58:39     self._send_request(method, url, body, headers, encode_chunked)
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2022-12-16 20:58:39     self.endheaders(body, encode_chunked=encode_chunked)
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2022-12-16 20:58:39     self._send_output(message_body, encode_chunked=encode_chunked)
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2022-12-16 20:58:39     self.send(msg)
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 975, in send
2022-12-16 20:58:39     self.connect()
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 1447, in connect
2022-12-16 20:58:39     super().connect()
2022-12-16 20:58:39   File "/usr/lib/python3.10/http/client.py", line 941, in connect
2022-12-16 20:58:39     self.sock = self._create_connection(
2022-12-16 20:58:39   File "/usr/lib/python3.10/socket.py", line 845, in create_connection
2022-12-16 20:58:39     raise err
2022-12-16 20:58:39   File "/usr/lib/python3.10/socket.py", line 833, in create_connection
2022-12-16 20:58:39     sock.connect(sa)
2022-12-16 20:58:39 OSError: [Errno 113] No route to host
2022-12-16 20:58:39 
2022-12-16 20:58:39 During handling of the above exception, another exception occurred:
2022-12-16 20:58:39 
2022-12-16 20:58:39 Traceback (most recent call last):
2022-12-16 20:58:39   File "/app/utils.py", line 153, in get_user_agent
2022-12-16 20:58:39     driver = get_webdriver()
2022-12-16 20:58:39   File "/app/utils.py", line 70, in get_webdriver
2022-12-16 20:58:39     driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
2022-12-16 20:58:39   File "/app/undetected_chromedriver/__init__.py", line 242, in __init__
2022-12-16 20:58:39     patcher.auto()
2022-12-16 20:58:39   File "/app/undetected_chromedriver/patcher.py", line 127, in auto
2022-12-16 20:58:39     release = self.fetch_release_number()
2022-12-16 20:58:39   File "/app/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
2022-12-16 20:58:39     return LooseVersion(urlopen(self.url_repo + path).read().decode())
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
2022-12-16 20:58:39     return opener.open(url, data, timeout)
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
2022-12-16 20:58:39     response = self._open(req, data)
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
2022-12-16 20:58:39     result = self._call_chain(self.handle_open, protocol, protocol +
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
2022-12-16 20:58:39     result = func(*args)
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
2022-12-16 20:58:39     return self.do_open(http.client.HTTPSConnection, req,
2022-12-16 20:58:39   File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
2022-12-16 20:58:39     raise URLError(err)
2022-12-16 20:58:39 urllib.error.URLError: <urlopen error [Errno 113] No route to host>
2022-12-16 20:58:39 
2022-12-16 20:58:39 During handling of the above exception, another exception occurred:
2022-12-16 20:58:39 
2022-12-16 20:58:39 Traceback (most recent call last):
2022-12-16 20:58:39   File "/app/flaresolverr.py", line 91, in <module>
2022-12-16 20:58:39     flaresolverr_service.test_browser_installation()
2022-12-16 20:58:39   File "/app/flaresolverr_service.py", line 47, in test_browser_installation
2022-12-16 20:58:39     user_agent = utils.get_user_agent()
2022-12-16 20:58:39   File "/app/utils.py", line 157, in get_user_agent
2022-12-16 20:58:39     raise Exception("Error getting browser User-Agent. " + str(e))
2022-12-16 20:58:39 Exception: Error getting browser User-Agent. <urlopen error [Errno 113] No route to host>
2022-12-16 20:58:33 2022-12-16 20:58:33 INFO     FlareSolverr 3.0.0
2022-12-16 20:58:33 2022-12-16 20:58:33 INFO     Testing web browser installation...
2022-12-16 20:58:33 2022-12-16 20:58:33 INFO     Chrome major version: 108
2022-12-16 20:58:44 2022-12-16 20:58:44 INFO     FlareSolverr 3.0.0
2022-12-16 20:58:44 2022-12-16 20:58:44 INFO     Testing web browser installation...
2022-12-16 20:58:44 2022-12-16 20:58:44 INFO     Chrome major version: 108

```

**Comment by Deathnetworks** [comment]
1.

**Comment by JoeSophia** [comment]
Hello,

Same issue for me, anyway to solve it with docker ?

Thanks

**Comment by JoeSophia** [comment]
@Deathnetworks  can you help me ?

**Comment by Deathnetworks** [comment]
For me it was a anticheat issue, balls'ing up the works. Once that was turned off it worked as normal.
If that's not your issue, no clue
________________________________
